on:
  # trigger on pushes to the master branch and 1-alpha
  push:
    branches:
      - main
      - 1-alpha
  # trigger on all pull requests
  pull_request:
  # enable manual triggering
  workflow_dispatch:

name: CI

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env: {"RUSTFLAGS": "-D warnings"}
    strategy:
      matrix:
        toolchain:
          - "1.31"
          - "nightly"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      # Diagnostics
      - name: Show versions
        run: |
          rustc --version
          cargo --version

      # Build main crate
      - name: Build
        run: cargo build
      - name: Build (all features)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo build --all-features

      # Test main crate
      - name: Test
        if: ${{ matrix.toolchain != 'nightly' }} 
        run: cargo test
      - name: Test (all features)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo test --all-features

  # Check code formatting
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
